"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {ContactShadows,Environment,Float,OrbitControls} from "@react-three/drei";
import * as THREE from "three";
import {useEffect,useMemo,useRef,useState} from "react";
import {PATH,SAFE,pathIndex,Player,PlayerColor} from "../lib/game";
const C:Record<PlayerColor,string>={red:"#e53935",green:"#43a047",blue:"#1e88e5",yellow:"#fbc02d"};
const D:Record<PlayerColor,string>={red:"#8e1d22",green:"#1b612e",blue:"#12549b",yellow:"#9c7400"};
const P=PATH.map(([r,c])=>new THREE.Vector3(c-7,.72,r-7));
const L:Record<PlayerColor,[number,number][]>={red:[[1,7],[2,7],[3,7],[4,7],[5,7]],green:[[7,1],[7,2],[7,3],[7,4],[7,5]],yellow:[[13,7],[12,7],[11,7],[10,7],[9,7]],blue:[[7,13],[7,12],[7,11],[7,10],[7,9]]};
function slot(c:PlayerColor,i:number){const q:{[K in PlayerColor]:[number,number]}={red:[-4,-4],green:[4,-4],blue:[-4,4],yellow:[4,4]},b=q[c],dx=i%2?0.7:-0.7,dz=i>1?0.7:-0.7;return new THREE.Vector3(b[0]+dx,.72,b[1]+dz)}
function target(c:PlayerColor,p:number,i:number){if(p===0)return slot(c,i);if(p>=53){const a=L[c][Math.min(4,p-53)];return new THREE.Vector3(a[0]-7,.72,a[1]-7)}return P[(pathIndex(c,p)+52)%52]}
function Pawn({c,p,i,active,click}:{c:PlayerColor;p:number;i:number;active:boolean;click:()=>void}){const ref=useRef<THREE.Group>(null),[hover,setHover]=useState(false),t=useMemo(()=>target(c,p,i),[c,p,i]);const cur=useRef(t.clone());useFrame((_,dt)=>{if(!ref.current)return;cur.current.lerp(t,1-Math.pow(.0005,dt));const hop=Math.max(0,Math.sin(cur.current.distanceTo(t)*7))*0.12;ref.current.position.set(cur.current.x,cur.current.y+hop,cur.current.z);const s=active||hover?1.13:1;ref.current.scale.lerp(new THREE.Vector3(s,s,s),.2);if(active)ref.current.rotation.y+=dt*.7});return <group ref={ref} onClick={e=>{e.stopPropagation();click()}} onPointerOver={e=>{e.stopPropagation();setHover(true)}} onPointerOut={()=>setHover(false)}><mesh castShadow><cylinderGeometry args={[.38,.52,.22,20]}/><meshStandardMaterial color={C[c]} metalness={.18} roughness={.22} emissive={active?C[c]:"#000"} emissiveIntensity={active?.7:0}/></mesh><mesh castShadow position={[0,.38,0]}><sphereGeometry args={[.38,20,16]}/><meshStandardMaterial color={C[c]} metalness={.15} roughness={.2} emissive={active?C[c]:"#000"} emissiveIntensity={active?.55:0}/></mesh><mesh castShadow position={[0,.12,0]}><coneGeometry args={[.27,.48,20]}/><meshStandardMaterial color={C[c]} roughness={.24}/></mesh>{(active||hover)&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,-.04,0]}><ringGeometry args={[.55,.7,32]}/><meshBasicMaterial color={C[c]} transparent opacity={.5}/></mesh>}</group>}
function Home({c}:{c:PlayerColor}){const q:{[K in PlayerColor]:[number,number]}={red:[-4,-4],green:[4,-4],blue:[-4,4],yellow:[4,4]},a=q[c];return <group><mesh position={[a[0],.25,a[1]]} castShadow receiveShadow><boxGeometry args={[5.7,.5,5.7]}/><meshStandardMaterial color={D[c]} metalness={.25} roughness={.3}/></mesh><mesh position={[a[0],.54,a[1]]}><boxGeometry args={[5.1,.12,5.1]}/><meshStandardMaterial color={C[c]} emissive={C[c]} emissiveIntensity={.08} roughness={.28}/></mesh><mesh position={[a[0],.63,a[1]]}><boxGeometry args={[4.45,.12,4.45]}/><meshStandardMaterial color="#f6f7fb" roughness={.2}/></mesh></group>}
function star(){const s=new THREE.Shape();for(let i=0;i<10;i++){const a=i*Math.PI/5-Math.PI/2,r=i%2?.11:.26,x=Math.cos(a)*r,z=Math.sin(a)*r;i?s.lineTo(x,z):s.moveTo(x,z)}s.closePath();return s}
function Track(){const sh=useMemo(()=>star(),[]);return <group>{PATH.map(([r,c],i)=><group key={i} position={[c-7,.53,r-7]}><mesh castShadow receiveShadow><boxGeometry args={[.9,.3,.9]}/><meshStandardMaterial color="#eef1f6" roughness={.27}/></mesh>{SAFE.includes(i)&&<Float speed={1.4}><mesh position={[0,.2,0]} rotation={[-Math.PI/2,0,0]}><shapeGeometry args={[sh]}/><meshStandardMaterial color="#7180ff" emissive="#5264ff" emissiveIntensity={1.4}/></mesh></Float>}</group>)}</group>}
function Center(){return <group><mesh position={[0,.45,0]} castShadow><boxGeometry args={[3.05,.45,3.05]}/><meshStandardMaterial color="#111827" metalness={.35} roughness={.24}/></mesh>{(["red","green","yellow","blue"] as PlayerColor[]).map((c,i)=>{const a=i*Math.PI/2;return <mesh key={c} position={[Math.cos(a)*.72,.7,Math.sin(a)*.72]} rotation={[0,-a,0]}><coneGeometry args={[.92,.24,3]}/><meshStandardMaterial color={C[c]} emissive={C[c]} emissiveIntensity={.12}/></mesh>})}</group>}
function Dice({value,rolling}:{value:number;rolling:boolean}){const r=useRef<THREE.Mesh>(null);useFrame((_,dt)=>{if(!r.current)return;if(rolling){r.current.rotation.x+=dt*12;r.current.rotation.y+=dt*15;r.current.rotation.z+=dt*9}else{r.current.rotation.x=THREE.MathUtils.lerp(r.current.rotation.x,0,.14);r.current.rotation.z=THREE.MathUtils.lerp(r.current.rotation.z,0,.14);r.current.rotation.y=THREE.MathUtils.lerp(r.current.rotation.y,0,.14)}});return <group position={[0,2.5,0]}><mesh ref={r} castShadow><boxGeometry args={[1.05,1.05,1.05]}/><meshStandardMaterial color="#fff" roughness={.14}/></mesh><mesh position={[0,3.03,0]}><sphereGeometry args={[.08,12,8]}/><meshStandardMaterial color="#12182a"/></mesh><div/> </group>}
export default function Ludo3DBoard({players,turn,dice,rolling,onRoll,onToken}:{players:Player[];turn:number;dice:number;rolling:boolean;onRoll:()=>void;onToken:(p:number,id:number)=>void}){return <div className="threeBoard"><Canvas dpr={[1,1.5]} shadows camera={{position:[11,13,11],fov:38}} gl={{antialias:true,powerPreference:"high-performance"}}><color attach="background" args={["#070b18"]}/><ambientLight intensity={1.15}/><directionalLight castShadow position={[6,13,5]} intensity={3} shadow-mapSize={[1024,1024]}/><Environment preset="city" environmentIntensity={.3}/><mesh position={[0,-.15,0]} receiveShadow><boxGeometry args={[16.2,.35,16.2]}/><meshStandardMaterial color="#0c1326" metalness={.4} roughness={.3}/></mesh><Home c="red"/><Home c="green"/><Home c="blue"/><Home c="yellow"/><Track/><Center/>{players.flatMap((p,pi)=>p.tokens.map(t=><Pawn key={`${pi}-${t.id}`} c={p.color} p={t.progress} i={t.id} active={pi===turn&&!!dice&&(t.progress===0?dice===6:true)} click={()=>onToken(pi,t.id)}/>))}<Dice value={dice} rolling={rolling}/><ContactShadows position={[0,.05,0]} opacity={.35} scale={18} blur={2.5} far={10}/><OrbitControls enablePan={false} minDistance={12} maxDistance={21} minPolarAngle={.7} maxPolarAngle={1.2}/></Canvas><button className="threeRoll" onClick={onRoll} disabled={turn!==0||rolling||!!dice}>{rolling?"ROLLING…":dice?`RESULT ${dice}`:"ROLL DICE"}</button></div>}
